# Generated by Django 2.1.4 on 2019-02-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songname', models.CharField(max_length=20)),
                ('singer', models.CharField(max_length=20)),
                ('imagerurl', models.CharField(max_length=200)),
                ('songurl', models.CharField(max_length=250)),
                ('songmid', models.CharField(max_length=20)),
                ('lyric', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('topid', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='tagName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.Tag', verbose_name='分类'),
        ),
    ]
